version: '3.8'

services:
  PathCoRAG:
    build: .
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
    env_file:
      - .env
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - PathCoRAG_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  PathCoRAG_net:
    driver: bridge
